### ISSUE TITLE
2015 spring fling page

### ISSUE THREAD

**Issue by svmatthews** [cugos/cugos.github.com#100]
#### What should be on this page?

@powersa would you want to just take what you wrote in the google forum and revamp it for this page?

#### How should this page be built?

Either set as a meeting post or we could make a unique page and directory for `/spring-fling-2015` and just work on the index file there? I could whip together something relatively quickly that way (a la @thebigspoon but maybe less copyright infringement than last time :wink:) 

I'm worried that if we make the spring fling a meeting post, it could override the next upcoming meeting on the site since we'll have two "future" events on there. Might be worth testing out!

Here are some things to work on:

- [x] How to create a new event page
- [x] eventbrite?
- [x] put together "email template" to send to sponsors
- [x] put together email template for those to invite other people
- [x] page content - what should be on it?
- [x] homepage "alert" for upcoming event
- [x] navigation button

**Comment by powersa** [comment]
@svmatthews I'm in favor of making this a unique page, not a meeting post. 

The content at this point would essentially reflect the call that went on the forum and will continue to evolve as the event takes shape.

Feel free to whip something up and we can hack from there.

**Comment by svmatthews** [comment]
Great! This beckons the need for an alert option on the homepage to tell people about the spring fling!

**Comment by powersa** [comment]
"Public Service Announcement: CUGOS to coordinate and execute many geo hacks and cracks at the University of Washington on May 20th, 2015!"

**Comment by svmatthews** [comment]
... but mostly cracks!

**Comment by cliffordsnow** [comment]
How can I help?

**Comment by svmatthews** [comment]
Good question! We'd definitely like to plug it through the OSM community, if you wouldn't mind doing that. I think the dates are still being finalized, but @powersa and myself will put together a "sample email" if people want to share with their respective communities.

Bigger question: how would **you** like to help?

**Comment by svmatthews** [comment]
re: the page itself, I think creating a template for events would be really helpful i.e. `templates/events.html` so we can use it again? This will give us access to more front-matter and would be great for adding information as we progress.

**Comment by svmatthews** [comment]
@powersa is there an Eventbrite RSVP or anything? Happy to set one up if needed.

**Comment by svmatthews** [comment]
Alright, here's a screenshot of where we're at.

![screen shot 2015-03-30 at 7 29 08 pm](https://cloud.githubusercontent.com/assets/1943001/6911263/1c10a472-d713-11e4-9c67-1288282ff87b.png)

**Comment by svmatthews** [comment]
@aaronr you okay doing that talk? ^ ;)

**Comment by svmatthews** [comment]
Here's what the markup looks like for that event page:

```
---
layout: event
title: 2015 Spring Fling
event_date: May 20th, 2015
event_time: 9:00am - 4:00pm
event_location: University of Washington, Anderson Hall
event_header-image: header_cascadia.png
event_register-url: http://eventbrite.com/
event_schedule:
  -
    time: 9:00 AM
    title: Kickoff
    description: This is a thing with some things.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
  -
    time: 9:15 AM
    title: Talk by Aaron Racicot
    description: About CUGOS, about drone mapping, about brewing beer.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
  -
    time: 9:45 AM
    title: Open Source and what it means for you by ___________
    description: Sometimes you build things. Sometimes they build things. But everytime, we build things.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
  -
    time: 11:00 AM
    title: Hack proposals.
    description: Propose the hacks.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
  -
    time: 12:00 PM
    title: Lunch
    description: Think about the hacks.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
    extra_class: break
  -
    time: 12:30 PM
    title: Hack.
    description: Do the hacks.
    extra: "http://www.codeforamerica.org/media/images/people/ben-golder.jpg"
event_sponsors:
  -
    image: sponsor-uw.png
    link: http://www.washington.edu/
---

The CUGOS Spring Fling is a **full day events centered around open source geo**. This is an intensely educational learning session for passionate practitioners of all things open-source geospatial. If you care about geometry busting workflows, academic research brain dumps, parsing vertices while drinking beer, code as well as content, usability as well as design, then show up and eat free pizza. Join us for this special all-day-kinda event at the magical University of Washington Seattle Campus in place of our regular monthly meeting. BOOYA!

## Location

We'll be having our event at Anderson Hall, on the University of Washington campus.
```
